### ISSUE TITLE
需要适配qqnt 9.9.16.241104

### ISSUE THREAD

**Issue by cnxv** [sysrom/QQNTFileVerifyPatch#31]

**Comment by sysrom** [comment]
找不到这个版本号的QQ

**Comment by bluewzr** [comment]
需要适配9.9.16.29271这个版本的QQ

**Comment by sysrom** [comment]
![image](https://github.com/user-attachments/assets/811bf9af-d9dd-4ed0-8390-18a5a0ab73b7)

正常使用，无法复现问题，检查插件/框架是否适配了这个版本的QQ

**Comment by bluewzr** [comment]
已解决。&nbsp;


忝蠍【藍】
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月6日(星期三) 上午9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LiteLoaderQQNT/QQNTFileVerifyPatch] 需要适配qqnt 9.9.16.241104 (Issue #31)














 
image.png (view on web)
 
正常使用，无法复现问题，检查插件/框架是否适配了这个版本的QQ
